# Generated by Django 5.1.2 on 2025-06-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_profile_course_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="registration_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
