# Generated by Django 5.1.3 on 2024-12-04 13:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="access_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name="booking",
            name="qr_code",
            field=models.ImageField(
                blank=True, null=True, upload_to="booking_qrcodes/"
            ),
        ),
    ]
