# Generated by Django 5.1.3 on 2024-12-04 16:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_alter_booking_access_token_alter_booking_qr_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="access_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
