# Generated by Django 5.1.3 on 2024-12-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_alter_booking_access_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="booking",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
